### ISSUE TITLE
Method is doing more that one things

### ISSUE THREAD

**Issue by AlexKap23** [f-guevara/QuizMakerRepo#1]
https://github.com/f-guevara/QuizMakerRepo/blob/458595f15091aaad9ac7991dbfb970bf8f796415/ConsoleUI.cs#L12-L32

This method is not showing the menu as the name suggests but it's also getting user's input. In general each method should do only one thing but if you feel like this can be one method, you should change the name accordingly so that the code is clearer.

**Comment by f-guevara** [comment]
Issue resolved
