### ISSUE TITLE
Avoid having hardcoded strings as options. 

### ISSUE THREAD

**Issue by AlexKap23** [f-guevara/QuizMakerRepo#3]
https://github.com/f-guevara/QuizMakerRepo/blob/458595f15091aaad9ac7991dbfb970bf8f796415/ConsoleUI.cs#L58

In general hardcoded strings like this should be avoided. A constant should be declared for this as it's an option and in the future this might changes.

Messages DO NOT require constants. So you don't have to declare constant for every hardcoded string but for strings which are used in if cases or as options. 

There is at least one more occasion like this.

**Comment by f-guevara** [comment]
On a previous issue, I eliminated this part of the code, the user just enters "ESC" key to terminate the operation. Issue solved
