### ISSUE TITLE
You should not assume but you should let the user make the decisions

### ISSUE THREAD

**Issue by AlexKap23** [f-guevara/QuizMakerRepo#4]
https://github.com/f-guevara/QuizMakerRepo/blob/458595f15091aaad9ac7991dbfb970bf8f796415/ConsoleUI.cs#L72

In general you should not make assumptions in your code. Everything should be transparent. But if you need to make assumptions like those you should declare constants about those assumptions. So for example you can declare a constant that manages the maximum amount of answers or ask the user to provide this.

**Comment by f-guevara** [comment]
Enhancement: Allow users to specify the number of possible answers for each quiz question in ConsoleUI.GetNumberOfAnswers(). Issue solved
