### ISSUE TITLE
I would break down this method into more methods

### ISSUE THREAD

**Issue by AlexKap23** [f-guevara/QuizMakerRepo#5]
https://github.com/f-guevara/QuizMakerRepo/blob/458595f15091aaad9ac7991dbfb970bf8f796415/ConsoleUI.cs#L49-L117

How about splitting this into more methods for ease of readability and maintainability? 

For example a break down would be to 
1. for handling the question text
2. for handling the available answers
3. for handling the correct answer

**Comment by f-guevara** [comment]
Refactor: Break down EnterQuestions into smaller methods for readability and added option to exit using ESC key. Issue solved
