### ISSUE TITLE
You don't need multiple instances of this one

### ISSUE THREAD

**Issue by AlexKap23** [f-guevara/QuizMakerRepo#6]
https://github.com/f-guevara/QuizMakerRepo/blob/458595f15091aaad9ac7991dbfb970bf8f796415/QuizDataHandler.cs#L16

Each time Save or Load methods are used a new instance of this XmlSerializer serializer = new XmlSerializer(typeof(List<Question>));
is being created. 

How about declaring it  as a class level property and using it once?

This can be static and readonly.

**Comment by f-guevara** [comment]
Optimization: Declare XmlSerializer as a static readonly field to avoid repeated instantiation in SaveQuestions and LoadQuestions methods. Solved
