### ISSUE TITLE
Issues with this line

### ISSUE THREAD

**Issue by AlexKap23** [f-guevara/QuizMakerRepo#7]
https://github.com/f-guevara/QuizMakerRepo/blob/458595f15091aaad9ac7991dbfb970bf8f796415/QuizDataHandler.cs#L12

This is a constant so the name should be a follow the rules for constant names. It should be in all upper snake case so

FILE_PATH

Also why don't you create a file for all your constants? That will make your code much cleaner since you also have a lot of constants in your ConsoleUI class.

**Comment by f-guevara** [comment]
Changed the constant to FILE_PATH. Issue solved
